[2023-06-09T15:41:23.598+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v05.get_matplotlib scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09T15:41:23.604+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v05.get_matplotlib scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09T15:41:23.604+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-09T15:41:23.613+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2023-06-08 00:00:00+00:00
[2023-06-09T15:41:23.617+0000] {standard_task_runner.py:57} INFO - Started process 729 to run task
[2023-06-09T15:41:23.621+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v05', 'get_matplotlib', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpicrwrmfd']
[2023-06-09T15:41:23.624+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask get_matplotlib
[2023-06-09T15:41:23.690+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_python_dependencies_v05.get_matplotlib scheduled__2023-06-08T00:00:00+00:00 [running]> on host b7751f9cbebb
[2023-06-09T15:41:23.776+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='znawawi' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v05' AIRFLOW_CTX_TASK_ID='get_matplotlib' AIRFLOW_CTX_EXECUTION_DATE='2023-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-08T00:00:00+00:00'
[2023-06-09T15:41:23.779+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 17, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2023-06-09T15:41:23.790+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_dependencies_v05, task_id=get_matplotlib, execution_date=20230608T000000, start_date=20230609T154123, end_date=20230609T154123
[2023-06-09T15:41:23.803+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 27 for task get_matplotlib (No module named 'matplotlib'; 729)
[2023-06-09T15:41:23.834+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T15:41:23.852+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
