[2023-06-09T14:48:31.127+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09T14:48:31.132+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09T14:48:31.133+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 8
[2023-06-09T14:48:31.141+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-06-08 00:00:00+00:00
[2023-06-09T14:48:31.145+0000] {standard_task_runner.py:57} INFO - Started process 1454 to run task
[2023-06-09T14:48:31.151+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmphf7st1lo']
[2023-06-09T14:48:31.154+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask insert_into_table
[2023-06-09T14:48:31.214+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2023-06-08T00:00:00+00:00 [running]> on host 94560a00d375
[2023-06-09T14:48:31.289+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='znawawi' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-08T00:00:00+00:00'
[2023-06-09T14:48:31.290+0000] {sql.py:262} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-06-08', 'dag_with_postgres_operator_v03')
        
[2023-06-09T14:48:31.298+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-09T14:48:31.341+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-09T14:48:31.350+0000] {sql.py:375} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-06-08', 'dag_with_postgres_operator_v03')
        , parameters: None
[2023-06-09T14:48:31.353+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-06-08, dag_with_postgres_operator_v03) already exists.

[2023-06-09T14:48:31.362+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20230608T000000, start_date=20230609T144831, end_date=20230609T144831
[2023-06-09T14:48:31.369+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 28 for task insert_into_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-06-08, dag_with_postgres_operator_v03) already exists.
; 1454)
[2023-06-09T14:48:31.402+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T14:48:31.417+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
