[2023-06-09T14:37:32.641+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.create_postgres_table scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09T14:37:32.647+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.create_postgres_table scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09T14:37:32.648+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 7
[2023-06-09T14:37:32.659+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-06-08 00:00:00+00:00
[2023-06-09T14:37:32.662+0000] {standard_task_runner.py:57} INFO - Started process 616 to run task
[2023-06-09T14:37:32.666+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'create_postgres_table', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpdu5wunwc']
[2023-06-09T14:37:32.671+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask create_postgres_table
[2023-06-09T14:37:32.732+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.create_postgres_table scheduled__2023-06-08T00:00:00+00:00 [running]> on host 94560a00d375
[2023-06-09T14:37:32.796+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='znawawi' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-08T00:00:00+00:00'
[2023-06-09T14:37:32.797+0000] {sql.py:262} INFO - Executing: "
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag)id)
            )
        
[2023-06-09T14:37:32.805+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-09T14:37:32.853+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-09T14:37:32.863+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5433 failed: FATAL:  database "test" does not exist

[2023-06-09T14:37:32.871+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=create_postgres_table, execution_date=20230608T000000, start_date=20230609T143732, end_date=20230609T143732
[2023-06-09T14:37:32.881+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 10 for task create_postgres_table (connection to server at "host.docker.internal" (192.168.65.254), port 5433 failed: FATAL:  database "test" does not exist
; 616)
[2023-06-09T14:37:32.921+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T14:37:32.937+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
