[2023-06-09T15:18:10.257+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v04.get_sklearn scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-09T15:18:10.265+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v04.get_sklearn scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-09T15:18:10.266+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-09T15:18:10.277+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-06-07 00:00:00+00:00
[2023-06-09T15:18:10.283+0000] {standard_task_runner.py:57} INFO - Started process 266 to run task
[2023-06-09T15:18:10.290+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v04', 'get_sklearn', 'scheduled__2023-06-07T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpnk43ol0l']
[2023-06-09T15:18:10.294+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask get_sklearn
[2023-06-09T15:18:10.352+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_python_dependencies_v04.get_sklearn scheduled__2023-06-07T00:00:00+00:00 [running]> on host 48ad479a8416
[2023-06-09T15:18:10.438+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='znawawi' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v04' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T00:00:00+00:00'
[2023-06-09T15:18:10.439+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 13, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-06-09T15:18:10.448+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_dependencies_v04, task_id=get_sklearn, execution_date=20230607T000000, start_date=20230609T151810, end_date=20230609T151810
[2023-06-09T15:18:10.455+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 4 for task get_sklearn (No module named 'sklearn'; 266)
[2023-06-09T15:18:10.466+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T15:18:10.480+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
