[2023-06-08T21:05:47.092+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_v01.greet manual__2023-06-08T21:05:45.035083+00:00 [queued]>
[2023-06-08T21:05:47.097+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_v01.greet manual__2023-06-08T21:05:45.035083+00:00 [queued]>
[2023-06-08T21:05:47.098+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-08T21:05:47.104+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2023-06-08 21:05:45.035083+00:00
[2023-06-08T21:05:47.107+0000] {standard_task_runner.py:57} INFO - Started process 3336 to run task
[2023-06-08T21:05:47.110+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_v01', 'greet', 'manual__2023-06-08T21:05:45.035083+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow.py', '--cfg-path', '/tmp/tmphsc8kgyk']
[2023-06-08T21:05:47.112+0000] {standard_task_runner.py:85} INFO - Job 82: Subtask greet
[2023-06-08T21:05:47.143+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_taskflow_v01.greet manual__2023-06-08T21:05:45.035083+00:00 [running]> on host e3f9b08eb2c7
[2023-06-08T21:05:47.179+0000] {abstractoperator.py:597} ERROR - Exception rendering Jinja template for task 'greet', field 'op_kwargs'. Template: {'first_name': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'first_name'), 'last_name': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'last_name'), 'age': XComArg(<Task(_PythonDecoratedOperator): get_age>)}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_with_taskflow_v01 with key="first_name" is not found!
[2023-06-08T21:05:47.187+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_with_taskflow_v01 with key="first_name" is not found!
[2023-06-08T21:05:47.189+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_taskflow_v01, task_id=greet, execution_date=20230608T210545, start_date=20230608T210547, end_date=20230608T210547
[2023-06-08T21:05:47.195+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 82 for task greet (XComArg result from get_name at dag_with_taskflow_v01 with key="first_name" is not found!; 3336)
[2023-06-08T21:05:47.202+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-08T21:05:47.214+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
